name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Zip JP mod
        run: zip -r 01003C700009C000.zip romfs
      
      - name: Zip EU mod
        run: zip -r 0100F8F0000A2000.zip romfs
        
      - name: Zip US mod
        run: zip -r 01003BC0000A0000.zip romfs
