name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Choose a tag
      name:
        description: Release title
      body:
        description: Describe this release
      prerelease:
        type: choice
        description: This is a pre-release
        options:
        - true
        - false

jobs:
  release-mod:
    if: github.repository == '${{ github.repository_owner }}/Rainbow-Expansion'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Package EU mod files
        run: |
          Copy-Item -Path romfs-vanilla/ -Destination 0100F8F0000A2000/romfs -Recurse
          Copy-Item -Path romfs-octo/ -Destination 0100F8F0000A3065/romfs -Recurse
          7z a -tzip EU 0100F8F0000A2000 0100F8F0000A3065
          Remove-Item -Path 0100F8F0000A2000/romfs/Sound -Recurse
          Remove-Item -Path 0100F8F0000A3065/romfs/Sound -Recurse
          7z a -tzip EU_nomusic 0100F8F0000A2000 0100F8F0000A3065

      - name: Package JP mod files
        run: |
          Copy-Item -Path EU.zip -Destination JP.zip
          Copy-Item -Path EU_nomusic.zip -Destination JP_nomusic.zip
          7z rn -tzip JP 0100F8F0000A2000 01003C700009C000
          7z rn -tzip JP 0100F8F0000A3065 01003C700009D065
          7z rn -tzip JP_nomusic 0100F8F0000A2000 01003C700009C000
          7z rn -tzip JP_nomusic 0100F8F0000A3065 01003C700009D065

      - name: Package US mod files
        run: |
          Copy-Item -Path EU.zip -Destination US.zip
          Copy-Item -Path EU_nomusic.zip -Destination US_nomusic.zip
          7z rn -tzip US 0100F8F0000A2000 01003BC0000A0000
          7z rn -tzip US 0100F8F0000A3065 01003BC0000A1065
          7z rn -tzip US_nomusic 0100F8F0000A2000 01003BC0000A0000
          7z rn -tzip US_nomusic 0100F8F0000A3065 01003BC0000A1065

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.inputs.body }}
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            EU.zip
            EU_nomusic.zip
            JP.zip
            JP_nomusic.zip
            US.zip
            US_nomusic.zip
          name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.tag }}
