name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Choose a tag
      name:
        description: Release title
      body:
        description: Describe this release
      prerelease:
        type: choice
        description: This is a pre-release
        options:
          - true
          - false

permissions: write-all

jobs:
  release-mod:
    if: github.repository == '${{ github.repository_owner }}/Rainbow-Expansion'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package EU mod files
        run: |
          mkdir -p atmosphere/contents/0100F8F0000A2000 atmosphere/contents/0100F8F0000A3065
          mv romfs-vanilla atmosphere/contents/0100F8F0000A2000/romfs
          mv romfs-octo atmosphere/contents/0100F8F0000A3065/romfs
          zip -r0 EU atmosphere

          cp EU.zip EU_nomusic.zip
          zip -d EU_nomusic atmosphere/contents/0100F8F0000A2000/romfs/Sound/* atmosphere/contents/0100F8F0000A3065/romfs/Sound/*

      - name: Package JP mod files
        run: |
          mv atmosphere/contents/0100F8F0000A2000 atmosphere/contents/01003C700009C000
          mv atmosphere/contents/0100F8F0000A3065 atmosphere/contents/01003C700009D065
          zip -r0 JP atmosphere

          cp JP.zip JP_nomusic.zip
          zip -d JP_nomusic atmosphere/contents/01003C700009C000/romfs/Sound/* atmosphere/contents/01003C700009D065/romfs/Sound/*

      - name: Package US mod files
        run: |
          mv atmosphere/contents/01003C700009C000 atmosphere/contents/01003BC0000A0000
          mv atmosphere/contents/01003C700009D065 atmosphere/contents/01003BC0000A1065
          zip -r0 US atmosphere

          cp US.zip US_nomusic.zip
          zip -d US_nomusic atmosphere/contents/01003BC0000A0000/romfs/Sound/* atmosphere/contents/01003BC0000A1065/romfs/Sound/*

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.inputs.body }}
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            EU.zip
            EU_nomusic.zip
            JP.zip
            JP_nomusic.zip
            US.zip
            US_nomusic.zip
          name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.tag }}
