name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Choose a tag
      name:
        description: Release title
      body:
        description: Describe this release
      prerelease:
        type: choice
        description: This is a pre-release
        options:
        - true
        - false

jobs:
  release-mod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create mod zip files
        run: |
          mkdir 0100F8F0000A2000 0100F8F0000A3065
          
          cp -r romfs-vanilla/ 0100F8F0000A2000/romfs & cp -r romfs-octo/ 0100F8F0000A3065/romfs

          7z a -t7z EU 0100F8F0000A2000 0100F8F0000A3065
          7z a -tzip EU 0100F8F0000A2000 0100F8F0000A3065

          cp EU.7z JP.7z & cp EU.7z US.7z & cp EU.zip JP.zip & cp EU.zip US.zip

          7z rn JP.7z 0100F8F0000A2000 01003C700009C000
          7z rn JP.7z 0100F8F0000A3065 01003C700009D065
          7z rn JP.zip 0100F8F0000A2000 01003C700009C000
          7z rn JP.zip 0100F8F0000A3065 01003C700009D065
          7z rn US.7z 0100F8F0000A2000 01003BC0000A0000
          7z rn US.7z 0100F8F0000A3065 01003BC0000A1065
          7z rn US.zip 0100F8F0000A2000 01003BC0000A0000
          7z rn US.zip 0100F8F0000A3065 01003BC0000A1065

      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.inputs.body }}
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            EU.7z
            EU.zip
            JP.7z
            JP.zip
            US.7z
            US.zip
          name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.tag }}
