name: Work In Progress

on:
  push:
    branches: [ main ]
    paths:
      - 'romfs-octo/**'
      - 'romfs-vanilla/**'

  workflow_dispatch:

permissions: write-all

jobs:
  release-mod:
    if: github.repository == '${{ github.repository_owner }}/Rainbow-Expansion-Private'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package EU mod files
        run: |
          mkdir -p atmosphere/contents/0100F8F0000A2000 atmosphere/contents/0100F8F0000A3065
          mv romfs-vanilla atmosphere/contents/0100F8F0000A2000/romfs
          mv romfs-octo atmosphere/contents/0100F8F0000A3065/romfs
          zip -r0 EU atmosphere
 
      - name: Package JP mod files
        run: |
          mv atmosphere/contents/0100F8F0000A2000 atmosphere/contents/01003C700009C000
          mv atmosphere/contents/0100F8F0000A3065 atmosphere/contents/01003C700009D065
          zip -r0 JP atmosphere

      - name: Package US mod files
        run: |
          mv atmosphere/contents/01003C700009C000 atmosphere/contents/01003BC0000A0000
          mv atmosphere/contents/01003C700009D065 atmosphere/contents/01003BC0000A1065
          zip -r0 US atmosphere

      - name: GitHub release
        uses: ncfavier/action-gh-release@delete-existing
        with:
          body: Latest mod files for testers
          files: |
            EU.zip
            JP.zip
            US.zip
          name: Work In Progress
          tag_name: wip
          delete_on_existing: true
