name: WIP Release

on:
  push:
    branches: [ main ]
    paths:
      - 'romfs/**'

  workflow_dispatch:

jobs:
  release-mod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create mod zip files
        run: |
          mkdir 0100F8F0000A2000
          rsync -R romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm 0100F8F0000A2000

          mkdir 01003C700009C000
          rsync -R romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm 01003C700009C000

          mkdir 01003BC0000A0000
          rsync -R romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm 01003BC0000A0000

          mkdir 0100F8F0000A3065
          rsync -a romfs 0100F8F0000A3065 --exclude romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm --exclude romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm

          mkdir 01003C700009D065
          rsync -a romfs 01003C700009D065 --exclude romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm --exclude romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm

          mkdir 01003BC0000A1065
          rsync -a romfs 01003BC0000A1065 --exclude romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm --exclude romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm

          zip -r EU.zip 0100F8F0000A2000 0100F8F0000A3065

          zip -r JP.zip 01003C700009C000 01003C700009D065

          zip -r US.zip 01003BC0000A0000 01003BC0000A1065

      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          body: Latest mod files to test work-in-progress features
          prerelease: true
          files: |
            EU.zip
            JP.zip
            US.zip
          name: WIP
          tag_name: wip
          generate_release_notes: true
