name: WIP Release

on:
  push:
    branches: [ main ]
    paths:
      - 'romfs/**'

  workflow_dispatch:

jobs:
  release-mod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create mod zip files
        # EU base game
        run: mkdir 0100F8F0000A2000
        run: rsync -R romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm 0100F8F0000A2000
        #JP base game
        run: mkdir 01003C700009C000
        run: rsync -R romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm 01003C700009C000
        # US base game
        run: mkdir 01003BC0000A0000
        run: rsync -R romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm 01003BC0000A0000
        # EU octo expansion
        run: mkdir 0100F8F0000A3065
        run: rsync -a romfs 0100F8F0000A3065 --exclude romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm --exclude romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm
        # JP octo expansion
        run: mkdir 01003C700009D065
        run: rsync -a romfs 01003C700009D065 --exclude romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm --exclude romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm
        # US octo expansion
        run: mkdir 01003BC0000A1065
        run: rsync -a romfs 01003BC0000A1065 --exclude romfs/Sound/Resource/Stream/BaseNoise_Plaza.bfstm --exclude romfs/Sound/Resource/Stream/Plaza00_c_VS.bfstm
        # Zip EU mod
        run: zip -r EU.zip 0100F8F0000A2000 0100F8F0000A3065
        # Zip JP mod
        run: zip -r JP.zip 01003C700009C000 01003C700009D065
        # Zip US mod
        run: zip -r US.zip 01003BC0000A0000 01003BC0000A1065

      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          body: Latest mod files to test work-in-progress features
          prerelease: true
          files: |
            EU.zip
            JP.zip
            US.zip
          name: WIP
          tag_name: wip
          generate_release_notes: true
